name: factory_task
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  http: ^1.3.0
  image_picker: ^1.1.2

flutter:
  uses-material-design: true

  # Add your assets
  assets:
    - assets/images/

  # Uncomment and configure your fonts section correctly
  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
